version: "3"
services:
  rights:
    build: ./
    ports:
      - "5080:5080"
  db:
    image: postgres
    volumes:
      - ./files/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
